### ISSUE TITLE
Please add a LICENSE file to the repo as mentioned in the README

### ISSUE THREAD

**Issue by mbrukman** [livetrails/targetj#1]
First of all, thank you for building this project and sharing it with us!

The README says:

https://github.com/livetrails/targetj/blob/33bea6266fe2a211d3e8424369dd2563520f9bb4/README.md?plain=1#L184-L185

However, it refers to a `LICENSE` file which does not exist. Could you please add it?

You can find a copy of the MIT license here for easy copy-pasting: https://choosealicense.com/licenses/mit/

Thanks!

**Comment by livetrails** [comment]
Thank you for your feedback and for bringing this and I apologize for the oversight.

I have added the LICENSE file to the repository. You can find it at [License](https://github.com/livetrails/targetj/blob/main/License)

Thank you for for your help improving the project.

**Comment by mbrukman** [comment]
Thanks!
